server:
  port: 8888
  
spring:  application:    name: erudio-config-server      
  cloud:    config:      server:        git:          uri: https://github.com/manoelnetto06/erudio-config-server
          default-label: main
          search-paths:          - 'greeting-service*'
             